export const REMOTE_CONTROL_ACTIVE = 'REMOTE_CONTROL_ACTIVE';

export const UPDATE_REMOTE_CONTROL_SESSION = 'UPDATE_REMOTE_CONTROL_SESSION';

export const SET_RECEIVER_TRANSPORT = 'SET_RECEIVER_TRANSPORT';

export const SET_RECEIVER_ENABLED = 'SET_RECEIVER_ENABLED';

export const SET_CONTROLLER = 'SET_CONTROLLER';

export const SET_CONTROLLED_PARTICIPANT = 'SET_CONTROLLED_PARTICIPANT';

export const SET_REQUESTED_PARTICIPANT = 'SET_REQUESTED_PARTICIPANT';

